---
title: "B4"
author: "Nat"
date: "2023-12-06"
output: html_document
---
```{r}
library(tidyverse)
```

# Exercise 1

```{r}
library(tidytext)
library(janeaustenr)

#Choose book
full.book <- janeaustenr::prideprejudice

#Prepare text
book <- full.book
book <- paste(book, collapse = " ") #remove ""
book <- str_replace_all(book, pattern = "\\\\", replacement = "") # Remove slashes
book <- str_replace_all(book, pattern = "\\n", replacement = "") #Remove new line
book <- str_replace_all(book, pattern = "[:punct:]", replacement = "") #Remove punctuation
book <- tolower(book) #words that are in both capital and lowercase will not be double counted

book_df <- tibble(Text = book) #Make tibble for analysis

book_words <- book_df %>% 
    unnest_tokens(output = word, input = Text) 

book_words  <- book_words  %>%
    anti_join(stop_words) # Remove stop words 

#Word Counts
  
book_wordcounts <- book_words  %>% count(word, sort = TRUE)
use <- slice(book_wordcounts,(1:10))
use

#Plot data
ggplot(data = use, aes(y=n, x=word)) +
  geom_col(colour="black",fill="darkslategray4") +
  xlab("word") +
  ylab("times used") +
  ggtitle("Most Used Words - Pride and Prejudice")
```

# Assignment 2
```{r}

fig_latin <- function(word){
  if(!is.character(word) || length(word) != 1) {
    stop("input must a single word made of characters")
  }
  
  vowel <- c("a","e","i","o","u")
  consonant <- c("b", "c", "d", "f", "g", "h", "j", "k", "l", "m", "n", "p", "q", "r", "s", "t", "v", "w", "x", "y", "z")

  word <- tolower(word)
  
  #maybe adjust arrangement so it's more different from pig latin
  
  if (str_sub(word,1,1) %in% vowel) {
    body <- str_sub(word,2,-1)
    end <- str_sub(word,1,1)
    return(paste0("ta",body,"ta",end))
  }
  
  if (str_sub(word,1,1) %in% consonant) {
    body <- str_sub(word,2,-1)
    end <- str_sub(word,1,1)
    return(paste0("at",body,"ta",end))
  }
}

fig_latin("charge")

```








